// <auto-generated />
using System;
using ApiNET.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiNET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191226181537_OdataSample")]
    partial class OdataSample
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiNET.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("AddressNote");

                    b.Property<int>("AddressType");

                    b.Property<string>("BuildingName");

                    b.Property<string>("BuildingNumber");

                    b.Property<string>("Country");

                    b.Property<string>("County");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("FlatNumber");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("PostCode");

                    b.Property<string>("Street");

                    b.Property<string>("Town");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            AddressNote = "Dont post any letter",
                            AddressType = 0,
                            BuildingName = "MaviBalina Apt.",
                            BuildingNumber = "123",
                            Country = "Turkey",
                            County = "Istanbul",
                            CreateUser = "SYSTEM",
                            CustomerId = 1,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 632, DateTimeKind.Local).AddTicks(6035),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 632, DateTimeKind.Local).AddTicks(6038),
                            FlatNumber = "52",
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            PostCode = "34300",
                            Street = "Yenisehir",
                            Town = "Pendik"
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 1,
                            AddressNote = "",
                            AddressType = 1,
                            BuildingName = "Teknopark Istanbul",
                            BuildingNumber = "321",
                            Country = "Turkey",
                            County = "Istanbul",
                            CreateUser = "SYSTEM",
                            CustomerId = 1,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 632, DateTimeKind.Local).AddTicks(6086),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 632, DateTimeKind.Local).AddTicks(6087),
                            FlatNumber = "3",
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            PostCode = "34600",
                            Street = "Yenisehir",
                            Town = "Pendik"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<int>("CustomerRank");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("Name");

                    b.Property<string>("SurName");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 25,
                            CreateUser = "SYSTEM",
                            CustomerRank = 2,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 630, DateTimeKind.Local).AddTicks(9239),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 631, DateTimeKind.Local).AddTicks(6744),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Yunus Emre",
                            SurName = "Keskin"
                        },
                        new
                        {
                            Id = 2L,
                            Age = 18,
                            CreateUser = "SYSTEM",
                            CustomerRank = 0,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 631, DateTimeKind.Local).AddTicks(7086),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 631, DateTimeKind.Local).AddTicks(7093),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Yusuf Eren",
                            SurName = "Keskin"
                        },
                        new
                        {
                            Id = 3L,
                            Age = 45,
                            CreateUser = "SYSTEM",
                            CustomerRank = 4,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 631, DateTimeKind.Local).AddTicks(7098),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 631, DateTimeKind.Local).AddTicks(7098),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Ayşe Hacer",
                            SurName = "Keskin"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Email", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("EmailAddress");

                    b.Property<int>("EmailType");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            CreateUser = "SYSTEM",
                            CustomerId = 1,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 633, DateTimeKind.Local).AddTicks(1389),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 633, DateTimeKind.Local).AddTicks(1392),
                            EmailAddress = "yemrekeskin@gmail.com",
                            EmailType = 1,
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 0,
                            CreateUser = "SYSTEM",
                            CustomerId = 1,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 633, DateTimeKind.Local).AddTicks(1417),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 633, DateTimeKind.Local).AddTicks(1417),
                            EmailAddress = "info@yemrekeskin.com",
                            EmailType = 0,
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Designation");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<int>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ApiNET.Models.Phone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("AreaCode");

                    b.Property<string>("Country");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("Number");

                    b.Property<int>("PhoneType");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            AreaCode = "212",
                            Country = "90",
                            CreateUser = "SYSTEM",
                            CustomerId = 1,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 633, DateTimeKind.Local).AddTicks(7416),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 633, DateTimeKind.Local).AddTicks(7419),
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Number = "3786869",
                            PhoneType = 0
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 0,
                            AreaCode = "543",
                            Country = "90",
                            CreateUser = "SYSTEM",
                            CustomerId = 1,
                            DateCreated = new DateTime(2019, 12, 26, 21, 15, 36, 633, DateTimeKind.Local).AddTicks(7448),
                            DateModified = new DateTime(2019, 12, 26, 21, 15, 36, 633, DateTimeKind.Local).AddTicks(7448),
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Number = "5556677",
                            PhoneType = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
