// <auto-generated />
using System;
using ApiNET.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiNET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191112204810_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiNET.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("AddressNote");

                    b.Property<int>("AddressType");

                    b.Property<string>("BuildingName");

                    b.Property<string>("BuildingNumber");

                    b.Property<string>("Country");

                    b.Property<string>("County");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("FlatNumber");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("PostCode");

                    b.Property<string>("Street");

                    b.Property<string>("Town");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            AddressNote = "Dont post any letter",
                            AddressType = 0,
                            BuildingName = "MaviBalina Apt.",
                            BuildingNumber = "123",
                            Country = "Turkey",
                            County = "Istanbul",
                            CreateUser = "SYSTEM",
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 444, DateTimeKind.Local).AddTicks(2879),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 444, DateTimeKind.Local).AddTicks(2883),
                            FlatNumber = "52",
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            PostCode = "34300",
                            Street = "Yenisehir",
                            Town = "Pendik"
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 1,
                            AddressNote = "",
                            AddressType = 1,
                            BuildingName = "Teknopark Istanbul",
                            BuildingNumber = "321",
                            Country = "Turkey",
                            County = "Istanbul",
                            CreateUser = "SYSTEM",
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 444, DateTimeKind.Local).AddTicks(2926),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 444, DateTimeKind.Local).AddTicks(2926),
                            FlatNumber = "3",
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            PostCode = "34600",
                            Street = "Yenisehir",
                            Town = "Pendik"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.AddressMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AddressId");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<long>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("AddressMaps");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AddressId = 1L,
                            CreateUser = "SYSTEM",
                            CustomerId = 1L,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 444, DateTimeKind.Local).AddTicks(3962),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 444, DateTimeKind.Local).AddTicks(3964),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        },
                        new
                        {
                            Id = 2L,
                            AddressId = 2L,
                            CreateUser = "SYSTEM",
                            CustomerId = 1L,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 444, DateTimeKind.Local).AddTicks(3978),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 444, DateTimeKind.Local).AddTicks(3979),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<int>("CustomerRank");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("Name");

                    b.Property<string>("SurName");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 25,
                            CreateUser = "SYSTEM",
                            CustomerRank = 2,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 439, DateTimeKind.Local).AddTicks(9048),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 442, DateTimeKind.Local).AddTicks(7397),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Yunus Emre",
                            SurName = "Keskin"
                        },
                        new
                        {
                            Id = 2L,
                            Age = 18,
                            CreateUser = "SYSTEM",
                            CustomerRank = 0,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 443, DateTimeKind.Local).AddTicks(418),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 443, DateTimeKind.Local).AddTicks(427),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Yusuf Eren",
                            SurName = "Keskin"
                        },
                        new
                        {
                            Id = 3L,
                            Age = 45,
                            CreateUser = "SYSTEM",
                            CustomerRank = 4,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 443, DateTimeKind.Local).AddTicks(432),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 443, DateTimeKind.Local).AddTicks(433),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Ayşe Hacer",
                            SurName = "Keskin"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Email", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("EmailAddress");

                    b.Property<int>("EmailType");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            CreateUser = "SYSTEM",
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 445, DateTimeKind.Local).AddTicks(3679),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 445, DateTimeKind.Local).AddTicks(3682),
                            EmailAddress = "yemrekeskin@gmail.com",
                            EmailType = 1,
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 0,
                            CreateUser = "SYSTEM",
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 445, DateTimeKind.Local).AddTicks(3704),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 445, DateTimeKind.Local).AddTicks(3704),
                            EmailAddress = "info@yemrekeskin.com",
                            EmailType = 0,
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.EmailMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<long>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<long>("EmailId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("EmailMaps");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateUser = "SYSTEM",
                            CustomerId = 1L,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 445, DateTimeKind.Local).AddTicks(4716),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 445, DateTimeKind.Local).AddTicks(4717),
                            EmailId = 1L,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        },
                        new
                        {
                            Id = 2L,
                            CreateUser = "SYSTEM",
                            CustomerId = 1L,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 445, DateTimeKind.Local).AddTicks(4732),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 445, DateTimeKind.Local).AddTicks(4732),
                            EmailId = 2L,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Phone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("AreaCode");

                    b.Property<string>("Country");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("Number");

                    b.Property<int>("PhoneType");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            AreaCode = "212",
                            Country = "90",
                            CreateUser = "SYSTEM",
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 446, DateTimeKind.Local).AddTicks(5121),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 446, DateTimeKind.Local).AddTicks(5123),
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Number = "3786869",
                            PhoneType = 0
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 0,
                            AreaCode = "543",
                            Country = "90",
                            CreateUser = "SYSTEM",
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 446, DateTimeKind.Local).AddTicks(5148),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 446, DateTimeKind.Local).AddTicks(5149),
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Number = "5556677",
                            PhoneType = 2
                        });
                });

            modelBuilder.Entity("ApiNET.Models.PhoneMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<long>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<long>("PhoneId");

                    b.HasKey("Id");

                    b.ToTable("PhoneMaps");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateUser = "SYSTEM",
                            CustomerId = 1L,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 446, DateTimeKind.Local).AddTicks(6330),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 446, DateTimeKind.Local).AddTicks(6331),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            PhoneId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreateUser = "SYSTEM",
                            CustomerId = 1L,
                            DateCreated = new DateTime(2019, 11, 12, 23, 48, 10, 446, DateTimeKind.Local).AddTicks(6345),
                            DateModified = new DateTime(2019, 11, 12, 23, 48, 10, 446, DateTimeKind.Local).AddTicks(6345),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            PhoneId = 1L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
