// <auto-generated />
using System;
using ApiNET.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiNET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiNET.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("AddressNote");

                    b.Property<int>("AddressType");

                    b.Property<string>("BuildingName");

                    b.Property<string>("BuildingNumber");

                    b.Property<string>("Country");

                    b.Property<string>("County");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<long>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("FlatNumber");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("PostCode");

                    b.Property<string>("Street");

                    b.Property<string>("Town");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            AddressNote = "Dont post any letter",
                            AddressType = 0,
                            BuildingName = "MaviBalina Apt.",
                            BuildingNumber = "123",
                            Country = "Turkey",
                            County = "Istanbul",
                            CreateUser = "SYSTEM",
                            CustomerId = 0L,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 404, DateTimeKind.Local).AddTicks(2032),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 404, DateTimeKind.Local).AddTicks(2037),
                            FlatNumber = "52",
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            PostCode = "34300",
                            Street = "Yenisehir",
                            Town = "Pendik"
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 1,
                            AddressNote = "",
                            AddressType = 1,
                            BuildingName = "Teknopark Istanbul",
                            BuildingNumber = "321",
                            Country = "Turkey",
                            County = "Istanbul",
                            CreateUser = "SYSTEM",
                            CustomerId = 0L,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 404, DateTimeKind.Local).AddTicks(2082),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 404, DateTimeKind.Local).AddTicks(2083),
                            FlatNumber = "3",
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            PostCode = "34600",
                            Street = "Yenisehir",
                            Town = "Pendik"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<int>("CustomerRank");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("Name");

                    b.Property<string>("SurName");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 25,
                            CreateUser = "SYSTEM",
                            CustomerRank = 2,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 401, DateTimeKind.Local).AddTicks(1944),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 402, DateTimeKind.Local).AddTicks(674),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Yunus Emre",
                            SurName = "Keskin"
                        },
                        new
                        {
                            Id = 2L,
                            Age = 18,
                            CreateUser = "SYSTEM",
                            CustomerRank = 0,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 402, DateTimeKind.Local).AddTicks(9805),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 402, DateTimeKind.Local).AddTicks(9819),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Yusuf Eren",
                            SurName = "Keskin"
                        },
                        new
                        {
                            Id = 3L,
                            Age = 45,
                            CreateUser = "SYSTEM",
                            CustomerRank = 4,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 402, DateTimeKind.Local).AddTicks(9823),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 402, DateTimeKind.Local).AddTicks(9823),
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Name = "Ayşe Hacer",
                            SurName = "Keskin"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Email", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<long>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("EmailAddress");

                    b.Property<int>("EmailType");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            CreateUser = "SYSTEM",
                            CustomerId = 0L,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 404, DateTimeKind.Local).AddTicks(8120),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 404, DateTimeKind.Local).AddTicks(8122),
                            EmailAddress = "yemrekeskin@gmail.com",
                            EmailType = 1,
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 0,
                            CreateUser = "SYSTEM",
                            CustomerId = 0L,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 404, DateTimeKind.Local).AddTicks(8142),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 404, DateTimeKind.Local).AddTicks(8143),
                            EmailAddress = "info@yemrekeskin.com",
                            EmailType = 0,
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM"
                        });
                });

            modelBuilder.Entity("ApiNET.Models.Phone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivePassive");

                    b.Property<string>("AreaCode");

                    b.Property<string>("Country");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100);

                    b.Property<long>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(100);

                    b.Property<string>("Number");

                    b.Property<int>("PhoneType");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivePassive = 0,
                            AreaCode = "212",
                            Country = "90",
                            CreateUser = "SYSTEM",
                            CustomerId = 0L,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 405, DateTimeKind.Local).AddTicks(4725),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 405, DateTimeKind.Local).AddTicks(4728),
                            IsDefault = true,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Number = "3786869",
                            PhoneType = 0
                        },
                        new
                        {
                            Id = 2L,
                            ActivePassive = 0,
                            AreaCode = "543",
                            Country = "90",
                            CreateUser = "SYSTEM",
                            CustomerId = 0L,
                            DateCreated = new DateTime(2019, 11, 13, 22, 4, 23, 405, DateTimeKind.Local).AddTicks(4752),
                            DateModified = new DateTime(2019, 11, 13, 22, 4, 23, 405, DateTimeKind.Local).AddTicks(4753),
                            IsDefault = false,
                            IsDeleted = false,
                            ModifyUser = "SYSTEM",
                            Number = "5556677",
                            PhoneType = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
